[package]
name = "fast_thumbnail"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "fast_thumbnail"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.36"
fast_image_resize = { version = "5.1.2", features = ["image"] }
image = "0.24.4"
